const cheerio = require('cheerio')
const toMarkdown = require('to-markdown')

const parser = (bodyString, bodyFormatter = defaultBodyFormatter) => {
  const $ = cheerio.load(bodyString, { decodeEntities: false })

  return $('.journal-wrapper').toArray().map(journal => {
    journal = $(journal)

    return {
      title: journal.find('.metadata h2, .negate-box-margin h2').text().trim(),
      url: journal.find('.metadata h2 a, .negate-box-margin h2 a').attr('href'),
      date: new Date(journal.find('.metadata .author span, .timestamp').last().text()),
      body: bodyFormatter(journal.find('.gr-body .text').html())
    }
  })
}

const markdownBodyFormatter = body => {
  return toMarkdown(body, {
    converters: [
      // Manually remove <span> tags, as toMarkdown doesn't, and they can appear
      // in the HTML generated by Last.fm's BBCode markup
      { filter: 'span', replacement: content => content },
      // Drop script tags
      { filter: 'script', replacement: content => '' }
    ]
  })
}
const defaultBodyFormatter = markdownBodyFormatter

module.exports = parser
